"""Add public_token and lead_interests

Revision ID: 35fa60b8d011
Revises: f637419b85c0
Create Date: 2026-05-15 12:26:54.383771

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '35fa60b8d011'
down_revision: Union[str, None] = 'f637419b85c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lead_interests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=True),
    sa.Column('lead_token', sa.String(), nullable=True),
    sa.Column('company_name', sa.String(), nullable=False),
    sa.Column('contact_name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('segment', sa.String(), nullable=True),
    sa.Column('preferred_contact_time', sa.String(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('consent', sa.Boolean(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lead_interests_id'), 'lead_interests', ['id'], unique=False)
    op.create_index(op.f('ix_lead_interests_lead_id'), 'lead_interests', ['lead_id'], unique=False)
    op.create_index(op.f('ix_lead_interests_lead_token'), 'lead_interests', ['lead_token'], unique=False)
    op.add_column('leads', sa.Column('public_token', sa.String(length=32), nullable=True))
    op.create_index(op.f('ix_leads_public_token'), 'leads', ['public_token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_leads_public_token'), table_name='leads')
    op.drop_column('leads', 'public_token')
    op.drop_index(op.f('ix_lead_interests_lead_token'), table_name='lead_interests')
    op.drop_index(op.f('ix_lead_interests_lead_id'), table_name='lead_interests')
    op.drop_index(op.f('ix_lead_interests_id'), table_name='lead_interests')
    op.drop_table('lead_interests')
    # ### end Alembic commands ###
