"""Add logs

Revision ID: f637419b85c0
Revises: db0b3d2745b2
Create Date: 2026-05-14 18:36:57.682560

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f637419b85c0'
down_revision: Union[str, None] = 'db0b3d2745b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campaign_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('level', sa.String(), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campaign_logs_campaign_id'), 'campaign_logs', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_campaign_logs_id'), 'campaign_logs', ['id'], unique=False)
    op.add_column('campaigns', sa.Column('total_found', sa.Integer(), server_default='0', nullable=False))
    op.add_column('campaigns', sa.Column('total_saved', sa.Integer(), server_default='0', nullable=False))
    op.add_column('campaigns', sa.Column('total_duplicates', sa.Integer(), server_default='0', nullable=False))
    op.add_column('campaigns', sa.Column('total_errors', sa.Integer(), server_default='0', nullable=False))
    op.add_column('campaigns', sa.Column('finished_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('campaigns', 'finished_at')
    op.drop_column('campaigns', 'total_errors')
    op.drop_column('campaigns', 'total_duplicates')
    op.drop_column('campaigns', 'total_saved')
    op.drop_column('campaigns', 'total_found')
    op.drop_index(op.f('ix_campaign_logs_id'), table_name='campaign_logs')
    op.drop_index(op.f('ix_campaign_logs_campaign_id'), table_name='campaign_logs')
    op.drop_table('campaign_logs')
    # ### end Alembic commands ###
